### ISSUE TITLE
SharedConnection causes `broken pipe`

### ISSUE THREAD

**Issue by hadashiA** [mitsuhiko/redis-rs#220]
I want to share an instance of SharedConnection.
But this always return error `broken pipe`  after completed a future to establish connection.

Examples below:

```rust
   let client = redis::Client::open("redis://127.0.0.1:6379").unwrap();
    let connect = client.get_shared_async_connection();

    let conn = Runtime::new()
        .unwrap()
        .block_on(future::lazy( || {
            connect
        }))
        .unwrap();

    let (_, v): (_, Vec<u8>) = block_on_all(future::lazy(|| {
        redis::cmd("GET").arg("hoge").query_async(conn)
    })).unwrap(); // panics.
}
```

```
running 1 test
thread 'redis_cache' panicked at 'called `Result::unwrap()` on an `Err` value: broken pipe', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: test_cache::redis_cache
             at tests/test_cache.rs:39
  11: test_cache::redis_cache::{{closure}}
             at tests/test_cache.rs:22
  12: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
             at src/libtest/lib.rs:1468
test redis_cache ... FAILED

failures:

failures:
    redis_cache

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test test_cache'
```

**Comment by Marwes** [comment]
I think this might be because you run the connection under two different runtimes. If you run the query in the first Runtime that you created it should work

**Comment by hadashiA** [comment]
Oh... ok, I understand. Thanks for your response.

I tried to fix to use same runtime.

But..., I has been encountered an another problem that command sending is never completed...

Shared Connection instance living is means that Future is not  complete ??

Pleas tell me my mistakes...

```rust
pub struct RedisCache {
    client: redis::Client,
    pool: Arc<Mutex<Option<SharedConnection>>>,
}

impl RedisCache {
    pub fn new<T: IntoConnectionInfo>(url: T) -> Self {
        let client = redis::Client::open(url).unwrap();
        let pool = Arc::new(Mutex::new(None));
        RedisCache { client, pool }
    }

    fn checkout(&self) -> Box<Future<Item=SharedConnection, Error=RedisError> + Send> {
        let guard = self.pool.lock().unwrap();
        let pool_inner = self.pool.clone();

        if let Some(conn) = guard.clone() {
            Box::new(ok(conn))
        } else {
            let f = self.client.get_shared_async_connection()
                .map(move |conn| {
                    let mut guard = pool_inner.lock().unwrap();
                    (*guard).replace(conn.clone());
                    conn
                });
            Box::new(f)
        }
    }

    fn get(&self, key: &str) -> impl Future<Item=Option<Bytes>, Error=RedisError> {
        let key = key.to_string();


            .map(|(_, res): (_, Option<Vec<u8>>)| res.map(|x| Bytes::from(x)));
    }

}
```

```rust
let f = cache.checkout()
    .and_then(|conn| {
        redis::cmd("GET").arg("aaa") .query_async(conn)
    })
    .map(move |_| ())
    .map_err(|err| panic!("{}", err));

tokio::run(f);  // !!!!!! HUNGING UP !!!!!!!!
```

**Comment by Marwes** [comment]
I believe that is fixed by https://github.com/mitsuhiko/redis-rs/pull/217 , you can use git master until it is released in the next version

**Comment by hadashiA** [comment]
Thanks info.
I tried it (https://github.com/mitsuhiko/redis-rs/commit/b79857296bc47f8632fd0183ddce84e5f54752fb), but still the above code is hung up. 🤔

**Comment by hadashiA** [comment]
Hmm. The hangup was resolved by adding code to drop the SharedConnection to the end of the future's chain.
I think Future will not complete as long as at least one SharedConnection reference remains.
Is this expected behavior? 🤔

**Comment by Marwes** [comment]
Yes, since your `RedisCache` object is still alive the task that runs the queries must be kept alive and tokio won't shutdown. The easiest way to avoid running into this is to make sure you only create the `RedisCache` inside a task with, for instance `future::lazy`

```rust
tokio::run(future::lazy(|| {
    let cache = RedisCache::new();
    // Use cache
    
    // Cache is dropped automatically and the task shutsdown since it doesn't escape the `tokio::run` scope
});
```

**Comment by hadashiA** [comment]
OK,
Thank you for teaching me. :)

This behavior is surprising for me who only knows c#, javascript, and other languages with an implicit async runtime.

( I hope the documentation shows an example to share connection.
Thanks a lot!
