### ISSUE TITLE
ConnectionManager lockup(?) in combine dependency(?)

### ISSUE THREAD

**Issue by Fishrock123** [mitsuhiko/redis-rs#512]
We have a ~2month uptime service that became stuck recently and never reconnected to redis.

Thankfully this was just a deploy bot to Slack. The downtime seems to have coincided with slacks api outage. (Maybe timed out requests upstream leaked some kind of resource?)

Here's the relevant thread stack from `gdb`. I have a core lying around that I may be able to extract more from if that is helpful.

```
#0  0x000056454797bc3b in combine::parser::Parser::parse_with_state () at library/std/src/panicking.rs:519
#1  0x000056454798d05e in combine::stream::decode () at library/std/src/panicking.rs:519
#2  0x000056454797fe60 in redis::parser::aio_support::ValueCodec::decode_stream () at library/std/src/panicking.rs:519
#3  0x000056454798025e in <redis::parser::aio_support::ValueCodec as tokio_util::codec::decoder::Decoder>::decode_eof () at library/std/src/panicking.rs:519
#4  0x000056454751bb8b in <tokio_util::codec::framed_impl::FramedImpl<T,U,R> as futures_core::stream::Stream>::poll_next () at library/std/src/panicking.rs:519
#5  0x00005645475283a4 in <redis::aio::PipelineSink<T,I,E> as futures_sink::Sink<redis::aio::PipelineMessage<SinkItem,I,E>>>::poll_flush () at library/std/src/panicking.rs:519
#6  0x00005645474c6ef4 in <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll () at library/std/src/panicking.rs:519
#7  0x00005645474cabca in <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll () at library/std/src/panicking.rs:519
#8  0x00005645474d4c8d in std::thread::local::LocalKey<T>::with () at library/std/src/panicking.rs:519
#9  0x00005645474f459d in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll () at library/std/src/panicking.rs:519
#10 0x0000564547517ffb in async_task::raw::RawTask<F,T,S>::run () at library/std/src/panicking.rs:519
#11 0x00005645479c33f0 in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll () at library/std/src/panicking.rs:519
#12 0x00005645479c3a11 in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll () at library/std/src/panicking.rs:519
#13 0x00005645479c0ab6 in async_io::driver::block_on () at library/std/src/panicking.rs:519
#14 0x00005645479b949e in async_global_executor::threading::thread_main_loop () at library/std/src/panicking.rs:519
#15 0x00005645479bad27 in std::sys_common::backtrace::__rust_begin_short_backtrace () at library/std/src/panicking.rs:519
#16 0x00005645479bb14b in core::ops::function::FnOnce::call_once{{vtable-shim}} () at library/std/src/panicking.rs:519
#17 0x0000564547a0581a in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546
#18 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546
#19 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#20 0x00007f26c91cf609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f26c8f9f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

My main hints are: 
1. Requests to endpoints using redis never complete.
2. gdb shows combine hits `library/std/src/panicking.rs`.
3. combine is used by redis-rs under aio
4. no redis connections were being made or maintained according to netstat and nc

-----

Edit: one other thing I forgot - strace showed this every ~5-10s

```
accept4(17, 0x7ffe5cf91d00, [128], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
```

**Comment by Marwes** [comment]
Which version is this? An issue like this was fixed in the last version.

**Comment by Fishrock123** [comment]
```toml
[[package]]
name = "redis"
version = "0.20.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0a32cb439c4e89c1e6415e5b3b23d9d8cc6dc1bf5a8cade19adbd5418de803be"
```

**Comment by Fishrock123** [comment]
Oh and also:
```

[[package]]
name = "combine"
version = "4.5.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cc4369b5e4c0cddf64ad8981c0111e7df4f7078f4d6ba98fb31f2e17c4c57b7e"
```

**Comment by Fishrock123** [comment]
ANother bit of info: apparently this deploy bot service was eating 100% cpu as this was happening.

**Comment by Marwes** [comment]
Update to 0.20.2 https://crates.io/crates/redis

**Comment by Fishrock123** [comment]
@Marwes Can you please push / tag / changelog 0.20.2 in github?
