### ISSUE TITLE
Resource temporarily unavailable (os error 11)

### ISSUE THREAD

**Issue by weihualiu** [mitsuhiko/redis-rs#513]
Redis Versoin:  redis = { version = "0.20.2", features = [ "cluster", "tokio-comp"] }

Operator System:   4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

Code is below:
```rust
    let nodes = vec![
        "redis://:123456@xxx.yyy.com:5601/",
        "redis://:123456@xxx.yyy.com:5602/",
        "redis://:123456@xxx.yyy.com:5603/",
        "redis://:123456@xxx.yyy.com:5604/",
        "redis://:123456@xxx.yyy.com:5605/",
        "redis://:123456@xxx.yyy.com:5606/",
    ];
    let client = ClusterClient::open(nodes).unwrap();
    let mut con = client.get_connection().unwrap();

    let _: () = con.set("key1", b"foo").unwrap();
    let x: String = redis::cmd("SET")
        .arg("key1")
        .arg("你好")
        .query(&mut con)
        .unwrap();
    println!("x={}", x);
    let _: () = con.set("test", "test_data").unwrap();
    let _: () = con.set("key1", "哈哈").unwrap();
    let _: () = con.set("key2", "haha").unwrap();
```

ouput error:
```
x=OK
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable (os error 11)', src/main.rs:30:41
stack backtrace:
   0:          0x81bea40 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:          0x81bea40 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x81bea40 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:          0x81bea40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:          0x81d9bef - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:          0x81bb2c5 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:          0x81c06fb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:          0x81c06fb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:          0x81c06fb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:          0x81c01cd - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:          0x81c0d0d - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:          0x81c08a7 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:          0x81beedc - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:          0x81c0809 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:          0x8046441 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:          0x80464d3 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:          0x8049fe9 - core::result::Result<T,E>::unwrap::hdcc3af3d253f0a60
                               at /home/dev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
  17:          0x804a6a0 - redis_test::main::h97d9621ebb59eaca
                               at /home/dev/redis_test/src/main.rs:30:17
  18:          0x804a89b - core::ops::function::FnOnce::call_once::h88b48d003830c598
                               at /home/dev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19:          0x804a7ae - std::sys_common::backtrace::__rust_begin_short_backtrace::haa48d86f76abf336
                               at /home/dev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  20:          0x8048b51 - std::rt::lang_start::{{closure}}::h77f72a0826b7035c
                               at /home/dev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  21:          0x81c110a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  22:          0x81c110a - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  23:          0x81c110a - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  24:          0x81c110a - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  25:          0x81c110a - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  26:          0x8048b30 - std::rt::lang_start::h53750eb0f0c260af
                               at /home/dev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  27:          0x804a79c - main
  28:     0x7fffff5870b3 - __libc_start_main
  29:          0x8046b7e - _start
  30:                0x0 - <unknown>
```

**Comment by Marwes** [comment]
This sounds like an issue on your redis server end, not in this client library.

**Comment by weihualiu** [comment]
> This sounds like an issue on your redis server end, not in this client library.

use redis-cli command:
```shell
dev@LAPTOP-J29U5AFE:~$ redis-cli -h xxx.yyy.com -p 5601 -a 123456 --raw -c
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
xxx.yyy.com:5601> get key2
world
xxx.yyy.com:5601> get key3
workday
xxx.yyy.com:5601> get key1
-> Redirected to slot [9189] located at xxx.yyy.com:5602
你好
xxx.yyy.com:5602> set key1 hello
OK
xxx.yyy.com:5602> set key2 world
-> Redirected to slot [4998] located at xxx.yyy.com:5601
OK
xxx.yyy.com:5601> set key3 workday
OK
xxx.yyy.com:5601>
```

redis cluster server is normal working.

**Comment by weihualiu** [comment]
my cluster nodes ip set domain error.
