### ISSUE TITLE
"broken pipe" since tokio-util 0.6.9

### ISSUE THREAD

**Issue by stephank** [mitsuhiko/redis-rs#558]
Since upgrading from tokio-util 0.6.8 to 0.6.9, I'm seeing 'broken pipe' errors. This is using redis crate 0.21.3 and a Tokio multiplexed connection. I'm able to reproduce it on both Linux and macOS.

Suspect this Tokio PR may have altered behavior the redis crate relied on: https://github.com/tokio-rs/tokio/pull/4166

I can also reproduce it on `master` using the test suite:

```sh
cargo update -p tokio-util
make test
```

Where before tests pass, now output looks like:

```
====================================================================
Testing Connection Type TCP with all features
====================================================================

[...]

     Running tests/test_async.rs (target/debug/deps/test_async-b353b5441961144f)

running 17 tests
test dont_panic_on_closed_multiplexed_connection ... ok
test invalid_password_issue_343 ... ok
test io_error_on_kill_issue_320 ... id=4 addr=127.0.0.1:49537 laddr=127.0.0.1:49528 fd=7 name=to-kill age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=45024 argv-mem=10 obl=0 oll=0 omem=0 tot-mem=62490 events=r cmd=client user=default redir=-1

ok
test pub_sub::automatic_unsubscription ... ok
test pub_sub::pub_sub_conn_reuse ... ok
test pub_sub::pub_sub_subscription ... ok
test pub_sub::pub_sub_unsubscription ... ok
test test_args ... ok
test test_args_multiplexed_connection ... ok
test test_args_with_errors_multiplexed_connection ... thread 'main' panicked at 'broken pipe', tests/test_async.rs:218:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
test test_async_scanning_big_batch ... ok
test test_async_scanning_small_batch ... ok
test test_pipeline_transaction ... ok
test test_pipeline_transaction_with_errors ... ok
test test_script ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: broken pipe', tests/test_async.rs:350:6
FAILED
test test_script_returning_complex_type ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: broken pipe', tests/test_async.rs:369:6
FAILED
test test_transaction_multiplexed_connection ... ok
```

**Comment by stephank** [comment]
Think I understand what's going wrong here. Will attempt to make a PR.
